# Generated by Django 3.2 on 2023-06-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_correct_answer', to='api.word', verbose_name='правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_question', to='api.word', verbose_name='вопрос')),
                ('uncorrect_answer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_uncorrect_answer1', to='api.word', verbose_name='первый неправильный ответ')),
                ('uncorrect_answer2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uncorrect_answer2', to='api.word', verbose_name='второй неправильный ответ')),
            ],
        ),
    ]
